export const baseTypeDefaultValue = {
  string: () => '',
  number: () => 0,
  boolean: () => false,
  array: () => [],
  object: () => ({}),
  map: () => new Map(),
  set: () => new Set(),
  function: () => () => {},
  asyncfunction: () => async () => {},
  date: () => new Date(),
  regexp: () => /(?:.)/,
  bigint: () => BigInt(0),
  symbol: () => Symbol(''),
  weakmap: () => new WeakMap(),
  weakset: () => new WeakSet(),
  promise: () => Promise.resolve(),
  error: () => new Error(' '),
  int8array: () => new Int8Array(),
  uint8array: () => new Uint8Array(),
  uint8clampedarray: () => new Uint8ClampedArray(),
  int16array: () => new Int16Array(),
  uint16array: () => new Uint16Array(),
  int32array: () => new Int32Array(),
  uint32array: () => new Uint32Array(),
  float32array: () => new Float32Array(),
  float64array: () => new Float64Array(),
  file: () => new File([], 'file'),
  blob: () => new Blob(),
};
